baseurl = "https://example.com/"
disableRSS = true
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-US"
theme = "hugo-sustain"
<<<<<<< HEAD
[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.png"
  author = "Chris Turner"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "username"
  Email         = "email@example.com"
  Twitter       = "username"
  LinkedIn      = "username"
  Stackoverflow = "username"

## Main Menu
=======
title = "Chris Turner"
>>>>>>> 74b7e3adcedd0f08c8027d65cb2106a9c81d9c5d
[[menu.main]]
identifier = "resume"
name = "resume"
url = "/resume/"
weight = 300
[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 200
[[menu.main]]
identifier = "blog"
name = "blog"
url = "/blog/"
weight = 100
[params]
author = "Chris Turner"
avatar = "profile.png"
custom_css = []
custom_js = []
description = "Describe your website"
[params.social]
email = "email@example.com"
github = "username"
linkedin = "username"
stackoverflow = "username"
twitter = "username"
[permalinks]
post = "/:year/:month/:day/:slug"
