Paginate = 4
baseURL = "/"
description = "Kube is a professional  and a responsive Hugo theme for developers and designers that offers a documentation section mixed with a landing page and a blog"
languageCode = "en-us"
theme = "kube"
title = "Kube for Hugo"
[[menu.main]]
name = "Faq"
url = "/faq/"
weight = -100
[[menu.main]]
name = "Blog"
url = "/blog/"
weight = -100
[[menu.main]]
name = "Docs"
url = "/docs/"
weight = -100
[params]
author = "newpixcom"
email = "myemail@myaddress.xxx"
github = ""
rsslink = "/index.xml"
twitter = ""
