baseurl = "https://example.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-US"
theme = "hugo-sustain"
title = "Chris Turner"
[[menu.main]]
identifier = "resume"
name = "resume"
url = "/resume/"
weight = 300
[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 200
[[menu.main]]
identifier = "blog"
name = "blog"
url = "/blog/"
weight = 100
[params]
author = "Chris Turner"
avatar = "profile.png"
custom_css = []
custom_js = []
description = "Describe your website"
[params.social]
email = "email@example.com"
github = "username"
linkedin = "username"
stackoverflow = "username"
twitter = "username"
[permalinks]
post = "/:year/:month/:day/:slug"
